import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import AppThemeProvider from "./Components/AppThemeProvider/appThemeProvider";
import DashboardLayoutBasic from "./Components/Dashbord/dashboard"; // Import the updated layout

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Practice App Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppThemeProvider>
          <div className="container">
            {/* Wrap the content in DashboardLayoutBasic */}
            <DashboardLayoutBasic>
              {children}
            </DashboardLayoutBasic>
          </div>
        </AppThemeProvider>
      </body>
    </html>
  );
}
